# Generated by Django 3.2 on 2021-05-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_cliente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='file/pdfs/'),
        ),
    ]
