# Generated by Django 3.2.1 on 2021-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_cliente_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
