# Generated by Django 3.2.1 on 2021-05-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_cliente_data_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_ins',
            field=models.DateField(),
        ),
    ]
