# Generated by Django 3.2 on 2021-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_cliente_data_ins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
                ('Iscrizione_albo', models.BooleanField()),
                ('Numero_iscrizione', models.CharField(max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/')),
                ('data_di_nascita', models.DateField()),
            ],
            options={
                'verbose_name': 'Professionista',
                'verbose_name_plural': 'Professionisti',
            },
        ),
    ]
